export const ERROR_CODES = {
  ALREADY_INITIALIZED: 'ALREADY_INITIALIZED',
  INVALID_OUTPUT: 'INVALID_OUTPUT',
  IO_ERROR: 'IO_ERROR',
  NO_RULES_GIVEN: 'NO_RULES_GIVEN',
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  INVALID_CONFIG_JSON: 'INVALID_CONFIG_JSON',
  INVALID_CONFIG_SCHEMA: 'INVALID_CONFIG_SCHEMA',
  OUTPUT_DIR_NOT_FOUND: 'OUTPUT_DIR_NOT_FOUND',
  UNKNOWN_RULES: 'UNKNOWN_RULES',
  IO_ERROR_WRITE_RULES: 'IO_ERROR_WRITE_RULES',
  IO_ERROR_WRITE_CONFIG: 'IO_ERROR_WRITE_CONFIG',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
